# Foundry Configuration File
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
# Compiler settings
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

# Testing settings
fuzz_runs = 256
gas_reports = ["*"]

# Chain settings
[rpc_endpoints]
scroll_sepolia = "https://sepolia-rpc.scroll.io"
